import sys
import re
from decimal import Decimal, ROUND_HALF_UP

def calculate_count(occurrence, runs):
    return 1 if occurrence == 1 else (occurrence - 1) * runs + 1

def extract_time(line, pattern):
    match = re.search(pattern, line)
    return float(match.group(1)) if match else None

def parse_times(filename, model_name, num_tokens, num_partitions, runs, occurrence):
    inference_times = []
    run_model_times = []
    total_server_times = []
    total_client_times = []
    network_times = []
    handshake = []
    handle_request = []
    partitions = [[] for _ in range(num_partitions)]

    count = calculate_count(occurrence, runs)
    model_match_index = 1
    run_count = 0
    minimum_stats = 4

    is_llm = "albert" in model_name or "gpt2" in model_name
    if ("inference_time_in_occlum_on_disk_aes.txt" in filename or "inference_time_in_occlum_memory_only_aes.txt" in filename) and is_llm:
        minimum_stats = 1

    with open(filename, 'r') as file:
        lines = file.readlines()

    for i in reversed(range(len(lines))):
        if f"Model: {model_name}" in lines[i]:
            if count == model_match_index:
                if lines[i+minimum_stats+1] == "\n":
                    if "Inference time to run a model:" not in lines[i+1]:
                        stats = minimum_stats
                    else:
                        continue
                elif "inference_time_in_occlum_memory_only_aes.txt" in filename and is_llm:
                    stats = 8
                else:
                    stats = 9
                
                lines_below = lines[i:i+stats+1+num_partitions]
                k = 0 
                for line in lines_below:
                    if num_partitions > 1 and f"Partition_{k}:" in line:
                        time = extract_time(line, rf"Partition_{k}: ([\d\.]+) ms")
                        if time is not None:
                            partitions[k].append(time)
                            k += 1
                    if "Inference time:" in line:
                        t = extract_time(line, r"Inference time: ([\d\.]+) ms")
                        if t: inference_times.append(t)

                    if "Inference time to run a model:" in line:
                        t = extract_time(line, r"Inference time to run a model: ([\d\.]+) ms")
                        if t: run_model_times.append(t)

                    if "Total time - server:" in line:
                        t = extract_time(line, r"Total time - server: ([\d\.]+) ms")
                        if t: total_server_times.append(t)

                    if "Total time - client:" in line:
                        t = extract_time(line, r"Total time - client: ([\d\.]+) ms")
                        if t: total_client_times.append(t); run_count += 1

                    if "Time to read request from client:" in line:
                        net = extract_time(line, r"Time to read request from client: ([\d\.]+) ms")

                    if "Time to write response to client:" in line:
                        net2 = extract_time(line, r"Time to write response to client: ([\d\.]+) ms")
                        if net is not None and net2 is not None:
                            network_times.append(net + net2)

                    if "Time to perform handshake:" in line:
                        t = extract_time(line, r"Time to perform handshake: ([\d\.]+) ms")
                        if t: handshake.append(t)

                    if "Time to process the request:" in line:
                        t = extract_time(line, r"Time to process the request: ([\d\.]+) ms")
                        if t: handle_request.append(t)
                if run_count == runs:
                    break
            else:
                model_match_index += 1
    if run_count != runs:
        return [], [], []
    
    return run_model_times, inference_times, total_client_times

def calculate_average(times, runs):
    return sum(times) / runs if runs else 0

def convert_to_int(value):
    return int(Decimal(value).quantize(0, ROUND_HALF_UP))

def convert_to_float(value):
    return float(Decimal(value).quantize(Decimal('0.1'), ROUND_HALF_UP))

def print_results(num_tokens, run_model_times, inference_times, total_client_times, runs):
    print(f"Number of tokens generated by the model: {num_tokens}")
    print(f"Average inference time to run a model: {convert_to_int(calculate_average(run_model_times, runs))} ms")
    print(f"Average inference time: {convert_to_int(calculate_average(inference_times, runs))} ms")
    print(f"Average total client time: {convert_to_int(calculate_average(total_client_times,runs))} ms")

def main():
    if len(sys.argv) != 7:
        print("Usage: python3 calculate_avg_time.py <file_name> <model> <number_tokens> <number_partitions> <runs> <occurrence>\n")
        sys.exit(1)

    filename = sys.argv[1]
    model_name = sys.argv[2]
    number_tokens = int(sys.argv[3])
    number_partitions = int(sys.argv[4])
    runs = int(sys.argv[5])
    occurrence = int(sys.argv[6])
    

    run_model_times, inference_times, total_client_times = parse_times(filename, model_name, number_tokens, number_partitions, runs, occurrence)
    print_results(number_tokens, run_model_times, inference_times, total_client_times, runs)
         
if __name__ == "__main__":
    main()