import re
import os
import sys
import subprocess
import numpy as np
import pandas as pd
from collections import OrderedDict
import matplotlib.pyplot as plt
from matplotlib.patches import Patch
import matplotlib.ticker as ticker

def change_configuration_name(configuration):
    return configuration.replace(" ", "-") if " " in configuration else configuration

def parse_time(configuration, model_name, inference_time, df, index):
    output_str = inference_time.decode('utf-8')
    match = re.search(r"Number of tokens generated by the model: (\d+)", output_str)
    if match:
        num_tokens = int(match.group(1))
    else:
        print("No match found.")
    if num_tokens > 0:
        metric = 's'
    else:
        metric = 'ms'

    numbers = re.findall(rf'(\d+\.\d{1}|\d+)\s*{metric}', output_str)
    numbers = [int(num) for num in numbers]

    df.loc[index] = [configuration, model_name.replace('.onnx', ''), num_tokens, *numbers]

def get_model_lists(size_models):
    if size_models == "small":
        return (
            ['squeezenet1.0-7', 'mobilenetv2-7', 'densenet-7', 'efficientnet-lite4-11'],
            ['SqueezeNet\n1.0', 'MobileNet\nV2', 'DenseNet\n121', 'EfficientNet\nLite4']
        )
    elif size_models == "large":
        return (
            ['inception-v3-12', 'resnet101-v2-7', 'resnet152-v2-7', 'efficientnet-v2-l-18'],
            ['Inception\nV3', 'ResNet101\nV2', 'ResNet152\nV2', 'EfficientNet\nV2']
        )
    elif size_models == "xlarge":
        return (
            ['gpt2', 'smol-llama-220M-GQA', 'mistral-300M', 'qwen2.5-0.5B'],
            ['GPT-2 (0.124B)', 'LLaMA 2 (0.22B)', 'Mistral (0.3B)', 'Qwen2.5 (0.5B)']
        )
    else:
        print("Wrong size of models!\n")
        exit(1)

def plot_whole_vs_partitions(df_total, size_models, text=False):
    models, labels = get_model_lists(size_models)
    fig, ax = plt.subplots(figsize=(16, 12)) # 15, 12 for dnns and other 3 llms alone
    bar_width, spacing = 0.3, 0.1
    colors = [
        '#54a1a1', 
        '#1f6f6f',
    ]

    if size_models == "xlarge":
        num_configurations = 3
        colors.append('#0d3c3c')
        colors = ['#d4876a', '#a63c1f', '#6e2010']
        df = df_total[
            (df_total['Configuration'] == 'SGX-on Disk') &
            (df_total['Number of tokens generated'] == final_num_tokens)
        ]
    else:
        num_configurations = 2
        df = df_total[df_total['Configuration'] == 'SGX-on Disk']
    positions = np.arange(len(models)) * (bar_width * num_configurations + spacing)
   
   
    for i, model in enumerate(models):
        base = df[df['Model'] == model]
        split = df[df['Model'] == model + '_split0']
        if not base.empty and not split.empty:
            
            if size_models == "xlarge":
                first_split = split.iloc[0]
                second_split = split.iloc[1]
                print(model, base['Total Client Time'].values[0], second_split['Total Client Time'], first_split['Total Client Time'])
                ax.bar(positions[i] + 0 * bar_width, base['Total Client Time'].values[0], bar_width, color=colors[0], edgecolor='black')
                ax.bar(positions[i] + 1 * bar_width, second_split['Total Client Time'], bar_width, color=colors[1], edgecolor='black')
                ax.bar(positions[i] + 2 * bar_width, first_split['Total Client Time'], bar_width, color=colors[2], edgecolor='black')
            else:
                ax.bar(positions[i] - bar_width / 2, base['Total Client Time'].values[0], bar_width, color=colors[0], edgecolor='black')
                ax.bar(positions[i] + bar_width / 2, split['Total Client Time'].values[0], bar_width, color=colors[1], edgecolor='black')

            if text:
                if size_models == "xlarge":
                    first_split = split.iloc[0]
                    second_split = split.iloc[1]
                    ax.text(positions[i] + 0 * bar_width, base['Total Client Time'].values[0] + 10, str(round(base['Total Client Time'].values[0], 2)), ha='center', va='bottom', fontsize=24)
                    ax.text(positions[i] + 1 * bar_width, second_split['Total Client Time'] + 10, str(round(second_split['Total Client Time'], 2)), ha='center', va='bottom', fontsize=24)
                    ax.text(positions[i] + 2 * bar_width, first_split['Total Client Time'] + 10, str(round(first_split['Total Client Time'], 2)), ha='center', va='bottom', fontsize=24)
                else:
                    ax.text(positions[i] - bar_width / 2, base['Total Client Time'].values[0] + 10, str(round(base['Total Client Time'].values[0], 2)), ha='center', va='bottom', fontsize=24)
                    ax.text(positions[i] + bar_width / 2, first_split['Total Client Time'].values[0] + 10, str(round(split['Total Client Time'].values[0], 2)), ha='center', va='bottom', fontsize=24)

    if size_models == "small":
        ax.set_ylabel('Inference Time (ms)', fontsize=43, labelpad=30)
        plt.ylim(0, 3000)
    elif size_models == "large":
        legend_handles = [
            Patch(facecolor=colors[0], edgecolor='black', linewidth=2, label=f'InferONNX (full model)'),
            Patch(facecolor=colors[1], edgecolor='black', linewidth=2, label=f'InferONNX (intra-op partitioning)'),
        ]
        ax.legend(handles=legend_handles, fontsize=34.5, loc='upper left', ncol=1)
    else:
        if size_models == "xlarge": 
            ax.set_ylabel('Time to First Token (s)', fontsize=43, labelpad=30)
        else:
            ax.set_ylabel('Inference Time (s)', fontsize=43, labelpad=30)
        legend_handles = [
            Patch(facecolor=colors[0], edgecolor='black', linewidth=2, label=f'Full model execution'),
            Patch(facecolor=colors[1], edgecolor='black', linewidth=2, label=f'Inter-op partitioning'),
            Patch(facecolor=colors[2], edgecolor='black', linewidth=2, label=f'Inter- & intra-op partitioning'),
        ]
        ax.legend(handles=legend_handles, title='ShardLLM', fontsize=31.5, title_fontsize=31.5, loc='upper left', ncol=1, edgecolor='grey', framealpha=1, handleheight=1.2) # 30.7, 30
        #plt.ylim(0,560)

    ax.set_xticks(np.arange(len(models)) * (0.3 * num_configurations + 0.1) + 2 * 0.3 / 2)
    ax.set_xticklabels(labels, fontsize=35) # 30 before
    plt.tick_params(axis='y', labelsize=40)
    plt.xticks(rotation=15) # 45 angle for DNNs

    # ax.spines['top'].set_linewidth(2)
    # ax.spines['bottom'].set_linewidth(2)
    # ax.spines['right'].set_linewidth(2)
    # ax.spines['left'].set_linewidth(2)
    
    plt.tight_layout()
    plt.savefig(f"{inferONNX_path}/results/figure5_LLMs_ttft_gpt.pdf", format='pdf')
    plt.show()

def plot_sgx_disk_vs_sgx_memory_vs_cpu(df_total, size_models, text=False):
    models, labels = get_model_lists(size_models)
    fig, ax = plt.subplots(figsize=(15, 12))
    bar_width, spacing = 0.3, 0.1
    
    colors = [
        '#B455FF',
        '#7020CC', #A237FF',
        #'#3A0080', #'#9019FF'
    ]
    if size_models != 'xlarge':
        colors.append('#3A0080')
        num_configurations = 3
    else:
        num_configurations = 2
    positions = np.arange(len(models)) * (bar_width * num_configurations + spacing)

    df_sgx_disk = df_total[
        (df_total['Configuration'] == 'SGX-on Disk') &
        (df_total['Number of tokens generated'] == final_num_tokens)
    ]
    df_sgx_on_memory = df_total[
        (df_total['Configuration'] == 'SGX-on Memory') &
        (df_total['Number of tokens generated'] == final_num_tokens)
    ]
    df_cpu_ssl = df_total[
        (df_total['Configuration'] == 'CPU-TLS/SSL enabled') &
        (df_total['Number of tokens generated'] == final_num_tokens)
    ]
    print(df_sgx_disk)
    print(df_sgx_on_memory)
    print(df_cpu_ssl)
    for i, model in enumerate(models):
        base = df_sgx_disk[df_sgx_disk['Model'] == model]
        base_memory = df_sgx_on_memory[df_sgx_on_memory['Model'] == model]
        base_without_sgx = df_cpu_ssl[df_cpu_ssl['Model'] == model]
        if not base.empty and not base_memory.empty and not base_without_sgx.empty:
            ax.bar(positions[i] + 0 * bar_width, base['Total Client Time'].values[0], bar_width, color=colors[0], edgecolor='black')
            ax.bar(positions[i] + 1 * bar_width, base_memory['Total Client Time'].values[0], bar_width, color=colors[1], edgecolor='black')
            if size_models != 'xlarge':
                ax.bar(positions[i] + 2 * bar_width, base_without_sgx['Total Client Time'].values[0], bar_width, color=colors[2], edgecolor='black')
            
            if text:
                ax.text(positions[i] + 0 * bar_width, base['Total Client Time'].values[0] + 10, str(round(base['Total Client Time'].values[0], 2)), ha='center', va='bottom', fontsize=24)
                ax.text(positions[i] + 1 * bar_width, base_memory['Total Client Time'].values[0] + 10, str(round(base_memory['Total Client Time'].values[0], 2)), ha='center', va='bottom', fontsize=24)
                if size_models != 'xlarge':
                    ax.text(positions[i] + 2 * bar_width, base_without_sgx['Total Client Time'].values[0] + 10, str(round(base_without_sgx['Total Client Time'].values[0], 2)), ha='center', va='bottom', fontsize=24)
    
    if size_models == "small":
        ax.set_ylabel('Inference Time (ms)', fontsize=43, labelpad=30)
        plt.ylim(0, 3000)
    elif size_models == "xlarge":
        ax.set_ylabel('Inference Time (ms)', fontsize=43, labelpad=30)
        legend_handles = [
            Patch(facecolor=colors[0], edgecolor='black', linewidth=2, label=f'InferONNX'),
            Patch(facecolor=colors[1], edgecolor='black', linewidth=2, label=f'InferONNX (in memory)'),
        ]
        ax.legend(handles=legend_handles, fontsize=36, loc='upper left', ncol=1)
    else:
        legend_handles = [
            Patch(facecolor=colors[0], edgecolor='black', linewidth=2, label=f'InferONNX'),
            Patch(facecolor=colors[1], edgecolor='black', linewidth=2, label=f'InferONNX (in mem)'),
            Patch(facecolor=colors[2], edgecolor='black', linewidth=2, label=f'InferONNX (in mem, w/o SGX)'),
        ]
        ax.legend(handles=legend_handles, fontsize=34.5, loc='upper left', ncol=1)
        
    #ax.set_xticks(positions + 2 * bar_width / 2)
    ax.set_xticks(positions + (num_configurations - 1) * bar_width / 2)
    ax.set_xticklabels(labels, fontsize=30)    
    ax.tick_params(axis='y', labelsize=40)
    plt.xticks(rotation=45)

    plt.tight_layout()
    plt.savefig(f"{inferONNX_path}/results/figure4_LLMs_{final_num_tokens}_tokens_copy.pdf", format='pdf')
    plt.show()

def table_cpu_memory_vs_cpu_disk(df_total):
    rows = []

    model_names = {
        'squeezenet1.0-7': 'SqueezeNet 1.0',
        'mobilenetv2-7': 'MobileNet V2',
        'densenet-7': 'DenseNet121',
        'efficientnet-lite4-11': 'EfficientNet Lite4',
        'inception-v3-12': 'Inception V3',
        'resnet101-v2-7': 'ResNet101 V2',
        'resnet152-v2-7': 'ResNet152 V2',
        'efficientnet-v2-l-18': 'EfficientNet V2'
    }

    for model in models:
        model = model[:-5]
        if 'split' in model: continue
        df_cpu_memory = df_total[df_total['Configuration'] == 'CPU-on Memory']
        df_cpu_disk = df_total[df_total['Configuration'] == 'CPU-on Disk']

        if (model in df_cpu_memory['Model'].values and model in df_cpu_disk['Model'].values):
            data_cpu_memory = df_cpu_memory[df_cpu_memory['Model'] == model]
            data_cpu_disk = df_cpu_disk[df_cpu_disk['Model'] == model]

            rows.append({
                'Model': model_names[model],
                'InferONNX-Memory only w/o SGX (ms)': str(round(data_cpu_memory['Total Client Time'].values[0], 2)),
                'InferONNX-on Disk w/o SGX (ms)': str(round(data_cpu_disk['Total Client Time'].values[0], 2)),
            })

    df_result = pd.DataFrame(rows)
    df_result.to_csv(f'{inferONNX_path}/results/table2.csv', index=False)

def plot_inference_time_breakdown(df_total):
    inference = []
    entire_inference = []
    selected_models = ["mobilenetv2-7.onnx", "densenet-7.onnx", "inception-v3-12.onnx", "resnet152-v2-7.onnx", "efficientnet-v2-l-18.onnx"]
    names = ['MobileNet\nV2', 'DenseNet121', 'Inception\nV3', 'ResNet152\nV2', 'EfficientNet\nV2'] 

    df_sgx_disk = df_total[df_total['Configuration'] == 'SGX-on Disk']
    for selected_model in selected_models:
        base = df_sgx_disk[df_sgx_disk['Model'] == selected_model[:-5]]
        if not base.empty:
            inference.append(base['Run Model Time'].values[0])
            entire_inference.append(base['Inference Time'].values[0])
    loading = np.array(entire_inference) - np.array(inference)


    index_models, width = np.arange(len(selected_models)) * 0.65, 0.375
    fig, ax = plt.subplots(figsize =(7, 3.25))
    p1 = plt.bar(index_models, loading, width, color ='#3594CC', edgecolor ='black')
    p2 = plt.bar(index_models, inference, width, color='#D31F11', edgecolor ='black', bottom = loading)

    plt.ylabel('Execution time (ms)', fontsize=14)
    plt.xticks(index_models, names, fontsize=13)
    plt.yticks(fontsize=13)  
    plt.legend((p1[0], p2[0]), ('Load and decrypt model', 'Inference process'), fontsize=14)

    ax.spines['top'].set_linewidth(1)
    ax.spines['right'].set_linewidth(1)
    ax.spines['bottom'].set_linewidth(1)
    ax.spines['left'].set_linewidth(1)

    plt.tight_layout()
    plt.savefig('results/figure1.pdf', format='pdf')
    
def create_df(large_models=False):
    files_ = files
    configurations_ = configurations
    if large_models:
        files_ = files[2:]
        configurations_ = configurations[2:]
    
    df_total = pd.DataFrame(columns=['Configuration', 'Model', 'Number of tokens generated', 'Run Model Time', 'Inference Time', 'Total Client Time'])
    index_df = 0
    index_model_split = -1
    previous_model = ""
    for model in models:
        if 'split' in model:
            index_model_split += 1
            number_partitions = num_partitions[index_model_split]
        else:
            number_partitions = 1

        if "albert" in model or "gpt" in model or "qwen" in model or "mistral" in model or "llama" in model:
            num_tokens = [1]
        else:
            num_tokens = [0]

        for tokens in num_tokens:
            index_config = 0
            for file in files_:
                if not os.path.exists(file):
                    index_config += 1
                    index_df += 1
                    continue

                if 'split' in model:
                    if "occlum_on_disk_aes" in file:
                        occurence = 2 if previous_model == model else 1
                        command = f"python3 {inferONNX_path}/scripts/calculate_avg_time.py " + file + " " + model + " " + str(tokens) + " " + str(number_partitions) + " " + str(number_of_runs) + " " + str(occurence)
                        previous_model = model
                    else:
                        index_config += 1
                        index_df += 1
                        continue
                else:
                    command = f"python3 {inferONNX_path}/scripts/calculate_avg_time.py " + file + " " + model + " " + str(tokens) + " 1 " + str(number_of_runs) + " 1"

                output = subprocess.Popen(command, stdout=subprocess.PIPE, shell=True)
                (inference_time, err) = output.communicate()
                if err:
                    print(f"Error executing command: {command}")
                    sys.exit(1)

                configuration = configurations_[index_config]
                parse_time(configuration, model, inference_time, df_total, index_df)
                index_config += 1
                index_df += 1

    return df_total

def create_plots(df_total): 
    #plot_whole_vs_partitions(df_total, 'small')
    #plot_whole_vs_partitions(df_total, 'large')
    plot_whole_vs_partitions(df_total, 'xlarge')
    
    #plot_sgx_disk_vs_sgx_memory_vs_cpu(df_total, 'small')
    #plot_sgx_disk_vs_sgx_memory_vs_cpu(df_total, 'large')
    #plot_sgx_disk_vs_sgx_memory_vs_cpu(df_total, 'xlarge', True)

    #table_cpu_memory_vs_cpu_disk(df_total)

    #plot_inference_time_breakdown(df_total)

def main():
    if len(sys.argv) != 5:
        print("Usage: python3 create_plots.py <inferONNX_path> <inter_partitions_folder> <intra_partitions_folder> <number_of_runs>")
        exit(1)

    global inferONNX_path, intra_partitions_folder, inter_partitions_folder, number_of_runs
    inferONNX_path = sys.argv[1]
    inter_partitions_folder = sys.argv[2]
    intra_partitions_folder = sys.argv[3]
    number_of_runs = sys.argv[4]

    os.makedirs(f"{inferONNX_path}/results", exist_ok=True)

    global models, model_names, files, configurations, num_partitions, final_num_tokens
    models = ["squeezenet1.0-7.onnx", "squeezenet1.0-7_split0.onnx", "mobilenetv2-7.onnx", "mobilenetv2-7_split0.onnx", 
            "densenet-7.onnx", "densenet-7_split0.onnx", "efficientnet-lite4-11.onnx", "efficientnet-lite4-11_split0.onnx",
            "inception-v3-12.onnx", "inception-v3-12_split0.onnx", "resnet101-v2-7.onnx", "resnet101-v2-7_split0.onnx",
            "resnet152-v2-7.onnx", "resnet152-v2-7_split0.onnx", "efficientnet-v2-l-18.onnx", "efficientnet-v2-l-18_split0.onnx",
            
            "gpt2.onnx", "gpt2_split0.onnx", "gpt2_split0.onnx", 
            "smol-llama-220M-GQA.onnx", "smol-llama-220M-GQA_split0.onnx", "smol-llama-220M-GQA_split0.onnx", 
            "mistral-300M.onnx", "mistral-300M_split0.onnx", "mistral-300M_split0.onnx",
            "qwen2.5-0.5B.onnx", "qwen2.5-0.5B_split0.onnx", "qwen2.5-0.5B_split0.onnx"]
    model_names = ['SqueezeNet', 'MobileNet\nV2', 'DenseNet\n121', 'EfficientNet\nLite4', 'Inception\nV3', 'ResNet101\nV2',
                'ResNet152\nV2', 'EfficientNet\nV2',
                
                "GPT-2 (0.124B)", "LLaMA 2 (0.22B)", "Mistral (0.3B)", "Qwen2.5 (0.5B)"]
    files = [f"{inferONNX_path}/src/server_without_tls/inference_time_cpu_on_disk_no_aes.txt",
            f"{inferONNX_path}/src/server_without_tls/inference_time_cpu_memory_only_no_aes.txt",
            f"{inferONNX_path}/src/server_with_tls/inference_time_outside_occlum_memory_only_no_aes.txt",
            f"{inferONNX_path}/src/server_with_tls/inference_time_in_occlum_memory_only_aes.txt",
            f"{inferONNX_path}/src/server_with_tls/inference_time_in_occlum_on_disk_aes_file_caching.txt"]
    configurations = ['CPU-on Disk', 'CPU-on Memory', 'CPU-TLS/SSL enabled', 'SGX-on Memory', 'SGX-on Disk']

    final_num_tokens = 1
    num_partitions = [0] * 8
    for model in models:
        if "split" in model or not os.path.exists(f'{inferONNX_path}/models/{model[:-5]}/{intra_partitions_folder}'):
            continue

        if "gpt" in model or "llama" in model or "qwen" in model or "mistral" in model:
            result = subprocess.run(f'ls {inferONNX_path}/models/{model[:-5]}/{inter_partitions_folder} | wc -w', shell=True, text=True, capture_output=True)
            num_partitions.append(int(result.stdout.strip()))

        result = subprocess.run(f'ls {inferONNX_path}/models/{model[:-5]}/{intra_partitions_folder} | wc -w', shell=True, text=True, capture_output=True)
        num_partitions.append(int(result.stdout.strip()))


    print(num_partitions)
    df_total = create_df(False)

    create_plots(df_total)

if __name__ == '__main__':
    main()